name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "10715a75-295b-468f-acb3-23c133b6f49e"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "YOUR_R2_BUCKET_NAME"
preview_bucket_name = "notes-files-preview"
